[package]
name = "oft"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
oft = "0xbc628ab9070b1ecb037b546cc61930ca78a8bc9d389c934ddc952eb943761112"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
